name: Build and Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        cd portfolio-WEB  # Cambia nella cartella giusta dove si trova package.json
        npm install

    - name: Build the Angular app
      run: |
        cd portfolio-WEB  # Assicurati che il build avvenga nella cartella giusta
        npm run build --prod

    - name: Deploy to GitHub Pages
      run: |
        cd portfolio-WEB  # Assicurati di essere nella cartella giusta
        npm run deploy
